---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r include=FALSE}
library(DBI)
connect_own<-function() {
  
  options(mysql = list(
    "host" = "localhost", 
    "port" = 3306,
    "user" = "abel",
    "password" = "T77vqlra$"
    
  ))
  
  
  db <- RMySQL::dbConnect(RMySQL::MySQL(), dbname = "PROYECTO_3",
                          host = options()$mysql$host, 
                          port = options()$mysql$port, user = options()$mysql$user, 
                          password = options()$mysql$password)  
  
  
  
  return(db)
}

con_own <- connect_own()
table <- dbReadTable(con_own, "Tabla_Proyecto_3")
data <- data.frame(table)
```

# Customer-segmentation

<!-- badges: start -->
<!-- badges: end -->

The goal of Customer-segmentation is to ...

***
## Importation and exploration of data

Let's look at the dataset to see if it has been loaded correctly and to see the name and type of the variables.


```{r echo=FALSE}
head(data)
```


We look at the summary of the data and the standard deviation of numeric variables.

```{r echo = FALSE}
summary(data)
```



```{r echo=FALSE}

paste("The standar deviation or the volatility of Age is: ",sd(data$Age))
paste("The standar deviation or the volatility of Annual Income is: ",sd(data$Annual.Income..k..))
paste("The standar deviation or the volatility of Spending Score is:",sd(data$Spending.Score..1.100.))

```


